export const POST_TOPICS = [
  { label: 'Frontend Development', value: 'frontend-development' },
  { label: 'Backend Development', value: 'backend-development' },
  { label: 'Full Stack Development', value: 'fullstack-development' },
  { label: 'React.js', value: 'react' },
  { label: 'Vue.js', value: 'vue' },
  { label: 'Angular', value: 'angular' },
  { label: 'Svelte', value: 'svelte' },
  { label: 'Ember.js', value: 'ember' },
  { label: 'Next.js', value: 'nextjs' },
  { label: 'Nuxt.js', value: 'nuxt' },
  { label: 'Gatsby.js', value: 'gatsby' },
  { label: 'Astro', value: 'astro' },
  { label: 'Node.js', value: 'nodejs' },
  { label: 'Express.js', value: 'express' },
  { label: 'Nest.js', value: 'nestjs' },
  { label: 'GraphQL', value: 'graphql' },
  { label: 'REST APIs', value: 'restapi' },
  { label: 'TypeScript', value: 'typescript' },
  { label: 'JavaScript', value: 'javascript' },
  { label: 'WebAssembly', value: 'webassembly' },
  { label: 'Serverless', value: 'serverless' },
  { label: 'Microservices', value: 'microservices' },
  { label: 'CI/CD', value: 'cicd' },
  { label: 'DevOps', value: 'devops' },
  { label: 'Docker', value: 'docker' },
  { label: 'Kubernetes', value: 'kubernetes' },
  { label: 'Cloud Computing', value: 'cloud-computing' },
  { label: 'Machine Learning', value: 'machine-learning' },
  { label: 'Artificial Intelligence', value: 'ai' },
  { label: 'Blockchain', value: 'blockchain' },
]

export const SKILLS = [
  { label: 'Frontend Development', value: 'frontend' },
  { label: 'Backend Development', value: 'backend' },
  { label: 'Full Stack Development', value: 'fullstack' },
  { label: 'React.js', value: 'react' },
  { label: 'Vue.js', value: 'vue' },
  { label: 'Angular', value: 'angular' },
  { label: 'Svelte', value: 'svelte' },
  { label: 'Ember.js', value: 'ember' },
  { label: 'Next.js', value: 'nextjs' },
  { label: 'Nuxt.js', value: 'nuxt' },
  { label: 'Gatsby.js', value: 'gatsby' },
  { label: 'Astro', value: 'astro' },
  { label: 'Node.js', value: 'nodejs' },
  { label: 'Express.js', value: 'express' },
  { label: 'Nest.js', value: 'nestjs' },
  { label: 'GraphQL', value: 'graphql' },
  { label: 'REST APIs', value: 'restapi' },
  { label: 'TypeScript', value: 'typescript' },
  { label: 'JavaScript', value: 'javascript' },
  { label: 'WebAssembly', value: 'webassembly' },
  { label: 'Serverless', value: 'serverless' },
  { label: 'Microservices', value: 'microservices' },
  { label: 'CI/CD', value: 'cicd' },
  { label: 'DevOps', value: 'devops' },
  { label: 'Docker', value: 'docker' },
  { label: 'Kubernetes', value: 'kubernetes' },
  { label: 'Cloud Computing', value: 'cloud' },
  { label: 'Machine Learning', value: 'machinelearning' },
  { label: 'Artificial Intelligence', value: 'ai' },
  { label: 'Blockchain', value: 'blockchain' },
]

export const CREATE_VACANCY_OPTIONS = [
  { label: 'Frontend Development', value: 'frontend' },
  { label: 'Backend Development', value: 'backend' },
  { label: 'Full Stack Development', value: 'fullstack' },
  { label: 'React.js', value: 'react' },
  { label: 'Vue.js', value: 'vue' },
  { label: 'Angular', value: 'angular' },
  { label: 'Svelte', value: 'svelte' },
  { label: 'Ember.js', value: 'ember' },
  { label: 'Next.js', value: 'nextjs' },
  { label: 'Nuxt.js', value: 'nuxt' },
  { label: 'Gatsby.js', value: 'gatsby' },
  { label: 'Astro', value: 'astro' },
  { label: 'Node.js', value: 'nodejs' },
  { label: 'Express.js', value: 'express' },
  { label: 'Nest.js', value: 'nestjs' },
  { label: 'GraphQL', value: 'graphql' },
  { label: 'REST APIs', value: 'restapi' },
  { label: 'TypeScript', value: 'typescript' },
  { label: 'JavaScript', value: 'javascript' },
  { label: 'WebAssembly', value: 'webassembly' },
  { label: 'Serverless', value: 'serverless' },
  { label: 'Microservices', value: 'microservices' },
  { label: 'CI/CD', value: 'cicd' },
  { label: 'DevOps', value: 'devops' },
  { label: 'Docker', value: 'docker' },
  { label: 'Kubernetes', value: 'kubernetes' },
  { label: 'Cloud Computing', value: 'cloud' },
  { label: 'Machine Learning', value: 'machinelearning' },
  { label: 'Artificial Intelligence', value: 'ai' },
  { label: 'Blockchain', value: 'blockchain' },
]
